### PR TITLE
Update podspecs + fix TextRecognition

### PR DESCRIPTION
**Pull request by catalinmiron**
Since there were differences between GoogleMLKit version, there was no way to use TextRecognition and FaceDetection on the same project.

### CODE REVIEW

**Comment by a7med-mahmoud** [comment]
Hi @catalinmiron, Thanks for the contribution!
I was wondering why not update all GoogleMLKit iOS dependencies' versions not only Face Detection, Text Recognition and Image Labeling?

**Comment by a7med-mahmoud** [comment]
I'll merge and resolve other related issues in another PR. Thanks for the contribution @catalinmiron!

**Comment by catalinmiron** [comment]
Hi @a7med-mahmoud, I am very sorry but I somehow missed you comment from above (maybe got lost in my inbox). I have created the PR only for these packages because this is what I'm using in the project kinda. Sorry for the confusion :(

**Comment by a7med-mahmoud** [comment]
No problem. Thanks for the contribution!
I did upgrade all native dependencies and added the other languages to Text Recognition's Android too.

**Pull request merged**
